custom:
  reset-password:
    token-validity-in-milliseconds: 86400000
    email-from-address: 'ddalgu2@naver.com'
    email-subject: 비밀번호 재설정
    email-text-format: |-
      [비밀번호 재설정]
      비밀번호 재설정을 위해 아래의 주소로 접속해주세요. 해당 주소는 %d시간 뒤에 만료됩니다.
      %s
