###
POST {{host}}/users
Content-Type: application/json

{
  "loginId": "test1234",
  "password": "password1234",
  "nickName": "테스트계정",
  "email": "test@test.com"
}

###
GET {{host}}/users
Authorization: Bearer {{auth_token}}

###
GET {{host}}/users/1
Authorization: Bearer {{auth_token}}

###
PUT {{host}}/users/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "loginId": "test1234",
  "password": "newPassword1234",
  "nickName": "newNickNm",
  "email": "new@test.com"
}

###
DELETE {{host}}/users/1
Authorization: Bearer {{auth_token}}
